apiVersion: v1
kind: Service
metadata:
  name: APP_NAME
  namespace: APP_NAMESPACE
  labels:
    app: APP_NAME
    backstage.io/kubernetes-id: APP_NAME
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: APP_NAME
