---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: alice
spec:
  profile:
    displayName: Alice Platform
    email: alice@example.invalid
  memberOf: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob
spec:
  profile:
    displayName: Bob Developer
    email: bob@example.invalid
  memberOf: []
